name: CI

on:
  push:
    branches:
      - main
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['15']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
